#!/bin/bash

# Activate virtual environment
if [ -d ".venv" ]; then
    source .venv/bin/activate
else
    echo "Virtual environment not found. Creating one..."
    uv .venv
    source .venv/bin/activate
    uv sync
fi

# uvicorn main:app --host 0.0.0.0 --port 8000 --reload
python -m fastapi dev app/main.py